version: '3.9'

services:
  server:
    build:
      context: ./packages/server
      target: development
    ports:
      - 8080:8080
    env_file: packages/server/.env
    volumes:
      - ./app/:/packages/server
      - node_modules:/node_modules
  web:
    build:
      context: ./packages/web
      target: development
    ports:
      - 3000:3000
    env_file: packages/web/.env

volumes:
  node_modules: {}